services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
    - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
  baby-grogu:
    build: .
    # command: python main.py 10
    command: python example.py
    volumes:
    - .:/usr/src/app
    init: true
  loki:
    image: grafana/loki:3.0.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:2.4.2
    command: [
      "--target=all",
      "--storage.trace.backend=local",
      "--storage.trace.local.path=/var/tempo",
      "--auth.enabled=false"
    ]
    stop_grace_period: 1s

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo