receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
        endpoint: collector:4318
exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ debug, loki ]
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp ]
